#
# This codecov.yml is the default configuration for
# all repositories on Codecov. You may adjust the settings
# below in your own codecov.yml in your repository.
#
coverage:
  precision: 1
  round: down
  range: 70...100

  status:
    # Learn more at http://docs.codecov.io/docs/codecov-yaml
    project: true
    patch:                      # pull requests only: this commit status will measure the
                                # entire pull requests Coverage Diff. Checking if the lines
                                # adjusted are covered at least X%.
      default:
        enabled: yes             # must be yes|true to enable this status
        target: 80%              # specify the target "X%" coverage to hit
        branches: null           # -> see "branch patterns" below
        threshold: 2.5           # allowed to drop X% and still result in a "success" commit status
        if_no_uploads: error     # will post commit status of "error" if no coverage reports we uploaded
                                 # options: success, error, failure
        if_not_found: success
        if_ci_failed: error

comment:
  layout: "header, diff"
  behavior: default  # update if exists else create new
